### ISSUE TITLE
ffmpeg hardware encoding on Rasbperry Pi

### ISSUE THREAD

**Issue by codmpm** [datarhei/restreamer#148]
First, thank you for the great work!

Could you maybe add Raspberry Pi [hardware acceleration for ffmpeg](http://www.redhenlab.org/home/the-cognitive-core-research-topics-in-red-hen/the-barnyard/hardware-encoding-with-the-raspberry-pi)? 

Currently I'm running Restreamer on a Pi4 with 30-50% cpu for 720p@25fps, 4MBit/s. I think the use of the Pi's hardware capabilities could lower this significantly.
Sadly I've bought a "newer" Logitech C920 USB Webcam which does not support direct mp4 output anymore 😔

![Bildschirmfoto 2020-03-15 um 10 48 55](https://user-images.githubusercontent.com/9745239/76756536-28711680-6786-11ea-9eba-d975897c5ca2.png)

The current ffmpeg version in Buster does already support hardware encodinding, as far as I could find out:

```
pi@raspberrypi:~ $  ffmpeg -decoders | grep mmal
ffmpeg version 4.1.4-1+rpt7~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --prefix=/usr --extra-version= [...] -arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
 V..... h264_mmal            h264 (mmal) (codec h264)
 V..... mpeg2_mmal           mpeg2 (mmal) (codec mpeg2video)
 V..... mpeg4_mmal           mpeg4 (mmal) (codec mpeg4)
 V..... vc1_mmal             vc1 (mmal) (codec vc1)
```

In the docker image (armv7l) a newer version of ffmpeg is used, but it seems that there is no hardware accelaration enabled: 

```
pi@raspberrypi:~ $ docker exec -it restreamer /bin/bash
root@c8503942def4:/restreamer# ffmpeg -decoders | grep mmal
ffmpeg version 4.1.5 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --bindir=/usr/local//bin --extra-cflags=-I/usr/local//include --extra-ldflags=-L/usr/local//lib --prefix=/usr/local/ --enable-nonfree --enable-gpl --enable-version3 --enable-libmp3lame --enable-libx264 --enable-openssl --enable-postproc --enable-small --enable-static --disable-debug --disable-doc --disable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
```

Also, the used codec has to be switched from `libx264` to `h264_omx`.

I'm no expert on this, especially not regarding docker. Only gathered what I've found an openend an issue.

Maybe it's possible for me to point the docker ffmpeg to the systems ffmpeg and edit the encoding parameters?

Thank you and cheers,
Patrik

**Comment by codmpm** [comment]
Meanwhile I've testet Restreamer on an abandoned Pentium G5400, which also has hardware h264 encoding, but `libx264` als used there. This wont use the hw acceleration from the CPU and thus resultiing in 30-40% cpu load.

If I'm not mistaken `libmfx` should be the right choice.
https://trac.ffmpeg.org/wiki/HWAccelIntro

Maybe it is usefull to simpley make the "wanted" `-codec:v` option accessible via an environment variable? Ok, `ffmpeg` must be compiled accordingly...

Just writing down my thoughts. Thanks :-)

**Comment by ioppermann** [comment]
@codmpm I was able to build a Docker image with MMAL and OMX support for Raspberry Pi 3 and Pi 4. The decoding and encoding parameter have been adjusted to decode a h264 stream with `h264_mmal` and to encode it with `h264_omx`.

# EXPERIMENTAL

```
docker pull datarhei/restreamer-rpi:0.6.2
```

It is recommended that you run the latest raspbian (buster, February 2020).

In order to enable hardware acceleration, you have to mount `/opt/vc` into the container and give privileges to it, e.g.

```
docker run -it --rm --name restreamer -e "RS_USERNAME=..." -e "RS_PASSWORD=..." -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db -v /opt/vc:/opt/vc --tmpfs /tmp/hls --privileged datarhei/restreamer-rpi:0.6.2
```

This is for "normal" operation where you pull in a stream, decode it, and encode it again.

In case you have a USB camera, you can follow the instructions from https://datarhei.github.io/restreamer/docs/guides-usb-camera.html, but also here you have to mount the directory `/opt/vc` **and** the device `/dev/vchiq` into the container. `--privileged` is not required here and shouldn't be used, e.g.

```
docker run -it --rm --name restreamer -e "RS_USERNAME=..." -e "RS_PASSWORD=..." -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db -v /opt/vc:/opt/vc --tmpfs /tmp/hls --device=/dev/vchiq --device /dev/video0:/dev/video --device /dev/snd -e "RS_USBCAM_AUDIO=true" -e "RS_USBCAM_AUDIODEVICE=1,0" -e RS_USBCAM_FPS=25 -e RS_USBCAM_WIDTH=640 -e RS_USBCAM_HEIGHT=480 -e RS_MODE=USBCAM datarhei/restreamer-rpi:0.6.2
```

The source code is in the branch `rpi`. If you want to build you own image, checkout the branch and use `Dockerfile-rpi`.

**Comment by codmpm** [comment]
Wow. Much appreciated. I'm currently heading for a vacation but I will test as soon as I get back.

Big thanks!

**Comment by codmpm** [comment]
Hey again. Sadly I could not get it to run.

I'm on the current buster and `apt full-upgrade`'d the whole system as well as did `rpi-update`to be on current firmware files.

```
pi@octopi:~ $ cat /etc/issue
Raspbian GNU/Linux 10 \n \l
```

This is what I came up with regarding the options, as I don't need audio atm: 

```
docker run -it --rm \
    --name restreamer \
    -e "RS_USERNAME=admin" \
    -e "RS_PASSWORD=admin" \
    -e "RS_MODE=USBCAM" \
    -e "RS_USBCAM_WIDTH=1280" \
    -e "RS_USBCAM_HEIGHT=720" \
    -e "RS_USBCAM_FPS=30" \
    -p 8080:8080 \
    -v /mnt/restreamer/db:/restreamer/db \
    -v /opt/vc:/opt/vc \
    --tmpfs /tmp/hls \
    --device /dev/vchiq \
    --device /dev/video0:/dev/video \
    datarhei/restreamer-rpi:0.6.2
```

But there seems to be a problem with accessing the usb device. Did I forget something?

```
> Restreamer@0.6.2 start /restreamer
> node ./src/start

[15-03-2020 11:14:07.273] [INFO ]      _       _             _           _ 
[15-03-2020 11:14:07.287] [INFO ]   __| | __ _| |_ __ _ _ __| |___   ___(_)
[15-03-2020 11:14:07.289] [INFO ]  / _  |/ _  | __/ _  |  __|  _  |/  _ | |
[15-03-2020 11:14:07.289] [INFO ] | (_| | (_| | || (_| | |  | | | |  __/| |
[15-03-2020 11:14:07.290] [INFO ] |_____|_____|_||_____|_|  |_| |_|____||_|
[15-03-2020 11:14:07.292] [INFO ] 
[15-03-2020 11:14:07.292] [INFO ] Restreamer v0.6.2
[15-03-2020 11:14:07.293] [INFO ] 
[15-03-2020 11:14:07.295] [INFO ] ENVIRONMENTS
[15-03-2020 11:14:07.296] [INFO ] More information in our Docs
[15-03-2020 11:14:07.296] [INFO ] 
[15-03-2020 11:14:07.298] [INFO ] [                   ENV] RS_NODEJS_PORT = 3000 (using default) - Webserver port of application.
[15-03-2020 11:14:07.298] [INFO ] [                   ENV] RS_NODEJS_ENV = prod (using default) - Node.js Environment ('dev' or 'prod').
[15-03-2020 11:14:07.299] [INFO ] [                   ENV] RS_LOGLEVEL = 3 (using default) - Logging level (0=no logging, 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG).
[15-03-2020 11:14:07.301] [INFO ] [                   ENV] RS_TIMEZONE = Europe/Berlin (using default) - Set the timezone. Accepts Olson timezone IDs.
[15-03-2020 11:14:07.301] [INFO ] [                   ENV] RS_SNAPSHOT_INTERVAL = 1m (using default) - Interval for new snapshots (in milliseconds, use suffix 's' for seconds, 'm' for minutes). Use a value of 0 to disable snapshots.
[15-03-2020 11:14:07.302] [INFO ] [                   ENV] RS_USERNAME = admin - Username for the backend.
[15-03-2020 11:14:07.303] [INFO ] [                   ENV] RS_PASSWORD = ****** - Password for the backend.
[15-03-2020 11:14:07.304] [INFO ] [                   ENV] RS_TOKEN =  (using default) - Token for pushing an RTMP stream.
[15-03-2020 11:14:07.305] [INFO ] [                   ENV] RS_DEBUG_HEAPDUMPS = false (using default) - Create heapdumps of application.
[15-03-2020 11:14:07.306] [INFO ] [                   ENV] RS_DEBUG = false (using default) - Enables debug reporting.
[15-03-2020 11:14:07.307] [INFO ] [                   ENV] RS_AUDIO = auto (using default) - Audio track handling: auto, none (remove audio), silence (force silence), aac (force AAC), mp3 (force MP3).
[15-03-2020 11:14:07.308] [INFO ] [                   ENV] RS_HTTPS = false (using default) - Enables HTTPS support for admin interface and embeddable player.
[15-03-2020 11:14:07.309] [INFO ] [                   ENV] RS_INPUTSTREAM =  (using default) - Automatically start pulling from this stream on a fresh Restreamer installation.
[15-03-2020 11:14:07.311] [INFO ] [                 NGINX] Starting ...
[15-03-2020 11:14:07.632] [INFO ] [                 NGINX] Successfully started
[15-03-2020 11:14:07.635] [INFO ] [        RestreamerData] Checking jsondb file...
[15-03-2020 11:14:07.722] [INFO ] [              publicIP] Retrieving public IP ...
[15-03-2020 11:14:07.740] [INFO ] [             Webserver] Starting ...
[15-03-2020 11:14:07.943] [INFO ] [             Webserver] Running on port 3000
[15-03-2020 11:14:07.954] [INFO ] [    repeatToLocalNginx] Start streaming
[15-03-2020 11:14:07.990] [INFO ] [              publicIP] Found public IP: 87.139.63.17
[15-03-2020 11:14:08.205] [INFO ] [       checkForUpdates] Update checking succeeded. No updates available
[15-03-2020 11:14:08.396] [ERROR] [                 NGINX] 44#0: *2 live: stream not found, client: 127.0.0.1, server: 0.0.0.0:1935
[15-03-2020 11:14:08.414] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream" in 6000ms
[15-03-2020 11:14:14.420] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream"
[15-03-2020 11:14:14.422] [INFO ] [    repeatToLocalNginx] Start streaming
[15-03-2020 11:14:27.232] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream" in 6000ms
[15-03-2020 11:14:33.240] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream"
[15-03-2020 11:14:33.242] [INFO ] [    repeatToLocalNginx] Start streaming
```

Thanks again and cheers!

**Comment by ioppermann** [comment]
@codmpm Please try to run the docker command as root, i.e. `sudo docker run ...`.

Also running `rpi-update` might have caused some problems, because I get such a warning. Could be that some drivers or a library has some bugs.
```
#############################################################
WARNING: 'rpi-update' updates to pre-releases of the linux 
kernel tree and Videocore firmware.

'rpi-update' should only be used if there is a specific 
reason to do so - for example, a request by a Raspberry Pi 
engineer.

DO NOT use 'rpi-update' as part of a regular update process.

##############################################################
```

`/opt/vc` looks like this on my system:

```
pi@raspberrypi4:~/restreamer $ ll /opt/vc
total 24
drwxr-xr-x  6 root root 4096 Feb 13 15:56 .
drwxr-xr-x  4 root root 4096 Mar 10 14:22 ..
drwxr-xr-x  2 root root 4096 Feb 13 15:55 bin
drwxr-xr-x 11 root root 4096 Feb 13 15:56 include
drwxr-xr-x  4 root root 4096 Feb 13 15:56 lib
drwxr-xr-x  3 root root 4096 Feb 13 15:56 src
```

Can you try to install raspbian from scratch? I have "Raspbian Buster Lite" installed (https://www.raspberrypi.org/downloads/raspbian/) and only ran `apt full-upgrade`.

**Comment by ioppermann** [comment]
I pushed a new `datarhei/restreamer-rpi:0.6.2` image where you will see the ffmpeg command and possibly errors during startup regarding the USB camera.

Please do a `docker pull datarhei/restreamer-rpi:0.6.2` again and restart the Docker container.

**Comment by codmpm** [comment]
Thank you for your held. I've pulled the new version:

```
pi@octopi:~ $ docker pull datarhei/restreamer-rpi:0.6.2
0.6.2: Pulling from datarhei/restreamer-rpi
fff3167bf8c7: Already exists 
0b2d648919df: Already exists 
01e8e2d8f880: Already exists 
da7b424e03b8: Already exists 
743dfc834a49: Already exists 
70494ff2bd3f: Already exists 
99df21657448: Already exists 
2dcd0a325088: Pull complete 
1a9a571f8d91: Pull complete 
d37f8ff16540: Pull complete 
Digest: sha256:f0140950335b18bfd3b70fe8b7eec924cd815c1fc1c3eb01829fc6d52feaee84
Status: Downloaded newer image for datarhei/restreamer-rpi:0.6.2
docker.io/datarhei/restreamer-rpi:0.6.2
```

and after that started docker with `sudo`: 

```
pi@octopi:~ $ sudo docker run -it --rm \
>     --name restreamer \
>     -e "RS_USERNAME=admin" \
>     -e "RS_PASSWORD=admin" \
>     -e "RS_MODE=USBCAM" \
>     -e "RS_USBCAM_WIDTH=1280" \
>     -e "RS_USBCAM_HEIGHT=720" \
>     -e "RS_USBCAM_FPS=30" \
>     -p 8080:8080 \
>     -v /mnt/restreamer/db:/restreamer/db \
>     -v /opt/vc:/opt/vc \
>     --tmpfs /tmp/hls \
>     --device /dev/vchiq \
>     --device /dev/video0:/dev/video \
>     datarhei/restreamer-rpi:0.6.2
[sudo] Passwort für pi: 

> Restreamer@0.6.2 start /restreamer
> node ./src/start

[16-03-2020 13:45:57.678] [INFO ]      _       _             _           _ 
[16-03-2020 13:45:57.692] [INFO ]   __| | __ _| |_ __ _ _ __| |___   ___(_)
[16-03-2020 13:45:57.693] [INFO ]  / _  |/ _  | __/ _  |  __|  _  |/  _ | |
[16-03-2020 13:45:57.695] [INFO ] | (_| | (_| | || (_| | |  | | | |  __/| |
[16-03-2020 13:45:57.696] [INFO ] |_____|_____|_||_____|_|  |_| |_|____||_|
[16-03-2020 13:45:57.697] [INFO ] 
[16-03-2020 13:45:57.697] [INFO ] Restreamer v0.6.2
[16-03-2020 13:45:57.698] [INFO ] 
[16-03-2020 13:45:57.699] [INFO ] ENVIRONMENTS
[16-03-2020 13:45:57.700] [INFO ] More information in our Docs
[16-03-2020 13:45:57.701] [INFO ] 
[16-03-2020 13:45:57.702] [INFO ] [                   ENV] RS_NODEJS_PORT = 3000 (using default) - Webserver port of application.
[16-03-2020 13:45:57.702] [INFO ] [                   ENV] RS_NODEJS_ENV = prod (using default) - Node.js Environment ('dev' or 'prod').
[16-03-2020 13:45:57.703] [INFO ] [                   ENV] RS_LOGLEVEL = 3 (using default) - Logging level (0=no logging, 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG).
[16-03-2020 13:45:57.704] [INFO ] [                   ENV] RS_TIMEZONE = Europe/Berlin (using default) - Set the timezone. Accepts Olson timezone IDs.
[16-03-2020 13:45:57.705] [INFO ] [                   ENV] RS_SNAPSHOT_INTERVAL = 1m (using default) - Interval for new snapshots (in milliseconds, use suffix 's' for seconds, 'm' for minutes). Use a value of 0 to disable snapshots.
[16-03-2020 13:45:57.705] [INFO ] [                   ENV] RS_USERNAME = admin - Username for the backend.
[16-03-2020 13:45:57.706] [INFO ] [                   ENV] RS_PASSWORD = ****** - Password for the backend.
[16-03-2020 13:45:57.707] [INFO ] [                   ENV] RS_TOKEN =  (using default) - Token for pushing an RTMP stream.
[16-03-2020 13:45:57.708] [INFO ] [                   ENV] RS_DEBUG_HEAPDUMPS = false (using default) - Create heapdumps of application.
[16-03-2020 13:45:57.709] [INFO ] [                   ENV] RS_DEBUG = false (using default) - Enables debug reporting.
[16-03-2020 13:45:57.709] [INFO ] [                   ENV] RS_AUDIO = auto (using default) - Audio track handling: auto, none (remove audio), silence (force silence), aac (force AAC), mp3 (force MP3).
[16-03-2020 13:45:57.710] [INFO ] [                   ENV] RS_HTTPS = false (using default) - Enables HTTPS support for admin interface and embeddable player.
[16-03-2020 13:45:57.711] [INFO ] [                   ENV] RS_INPUTSTREAM =  (using default) - Automatically start pulling from this stream on a fresh Restreamer installation.
[16-03-2020 13:45:57.712] [INFO ] [                 NGINX] Starting ...
[16-03-2020 13:45:58.026] [INFO ] [                 NGINX] Successfully started
[16-03-2020 13:45:58.029] [INFO ] [        RestreamerData] Checking jsondb file...
[16-03-2020 13:45:58.082] [INFO ] [              publicIP] Retrieving public IP ...
[16-03-2020 13:45:58.093] [INFO ] [             Webserver] Starting ...
[16-03-2020 13:45:58.200] [INFO ] [             Webserver] Running on port 3000
[16-03-2020 13:45:58.207] [INFO ] [    repeatToLocalNginx] Start streaming
[16-03-2020 13:45:58.367] [INFO ] [              publicIP] Found public IP: 87.139.63.17
[16-03-2020 13:45:58.490] [INFO ] [       checkForUpdates] Update checking succeeded. Update available
[16-03-2020 13:45:58.558] [ERROR] [                 NGINX] 32#0: *2 live: stream not found, client: 127.0.0.1, server: 0.0.0.0:1935
[16-03-2020 13:45:58.564] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream" in 6000ms
ffmpeg version 4.1.5 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --bindir=/usr/local//bin --extra-cflags=-I/usr/local//include --extra-ldflags=-L/usr/local//lib --prefix=/usr/local/ --enable-nonfree --enable-gpl --enable-version3 --enable-libmp3lame --enable-libx264 --enable-omx --enable-omx-rpi --enable-mmal --enable-openssl --enable-postproc --enable-small --enable-static --disable-debug --disable-doc --disable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[video4linux2,v4l2 @ 0x3503870] The driver changed the time per frame from 1/30 to 1/10
Input #0, video4linux2,v4l2, from '/dev/video':
  Duration: N/A, start: 95692.485245, bitrate: 147456 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 1280x720, 147456 kb/s, 10 fps, 10 tbr, 1000k tbn, 1000k tbc
Input #1, lavfi, from 'anullsrc=r=44100:cl=mono':
  Duration: N/A, start: 0.000000, bitrate: 352 kb/s
    Stream #1:0: Audio: pcm_u8, 44100 Hz, mono, u8, 352 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_omx))
  Stream #1:0 -> #0:1 (pcm_u8 (native) -> aac (native))
Press [q] to stop, [?] for help
[h264_omx @ 0x350b9f0] Using OMX.broadcom.video_encode
Output #0, flv, to 'rtmp://127.0.0.1:1935/live/usbcam.stream':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (h264_omx) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1280x720, q=2-31, 4882 kb/s, 30 fps, 1k tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.35.100 h264_omx
    Stream #0:1: Audio: aac ([10][0][0][0] / 0x000A), 44100 Hz, mono, fltp, 69 kb/s
    Metadata:
      encoder         : Lavc58.35.100 aac
[16-03-2020 13:46:04.568] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream"
[16-03-2020 13:46:04.569] [INFO ] [    repeatToLocalNginx] Start streaming
[16-03-2020 13:46:18.392] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream" in 6000ms
[16-03-2020 13:46:24.396] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream"
[16-03-2020 13:46:24.399] [INFO ] [    repeatToLocalNginx] Start streaming
[16-03-2020 13:46:36.769] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream" in 6000ms
[16-03-2020 13:46:42.775] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream"
[16-03-2020 13:46:42.777] [INFO ] [    repeatToLocalNginx] Start streaming
av_interleaved_write_frame(): Broken pipeB time=00:00:44.79 bitrate=1625.4kbits/s speed=0.987x    
    Last message repeated 1 times
[flv @ 0x350a670] Failed to update header with correct duration.
[flv @ 0x350a670] Failed to update header with correct filesize.
Error writing trailer of rtmp://127.0.0.1:1935/live/usbcam.stream: Broken pipe
frame=  460 fps= 10 q=-0.0 Lsize=    9008kB time=00:00:45.36 bitrate=1626.6kbits/s speed=0.987x    
video:9000kB audio:8kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000336%
[aac @ 0x350d020] Qavg: 65520.777
Exiting normally, received signal 2.
```

I've quitwith `CTRL-C` which lead to the broken pipe messages.

Will try on a clean raspbian install shortly....

**Comment by ioppermann** [comment]
The `Broken pipe` message is normal if you quit with `CTRL-C`. But the HW encoding seems to be in use and ffmpeg is producing proper output:

```
[h264_omx @ 0x350b9f0] Using OMX.broadcom.video_encode
Output #0, flv, to 'rtmp://127.0.0.1:1935/live/usbcam.stream':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (h264_omx) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1280x720, q=2-31, 4882 kb/s, 30 fps, 1k tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.35.100 h264_omx
    Stream #0:1: Audio: aac ([10][0][0][0] / 0x000A), 44100 Hz, mono, fltp, 69 kb/s
    Metadata:
      encoder         : Lavc58.35.100 aac
```

I don't see any reason why Restreamer can't connect to `rtmp://127.0.0.1/live/usbcam.stream`. If you expose port 1935 as well `-p 1935:1935` you should be able to play the stream with `ffplay` or VLC from `rtmp://x.x.x.x/live/usbcam.stream`, where `x.x.x.x` is the IP you your Pi.

**Comment by codmpm** [comment]
Hmm... still no luck. I've installed a vanilla Raspbian Lite and only installed Docker via `curl -fsSL https://get.docker.com -o - | sudo sh`.

I've also added the user `pi` to the docker group: `sudo usermod -aG docker $(id -un)`. Made no difference if I used `sudo` or not.

```
[16-03-2020 14:37:30.205] [INFO ] [    repeatToLocalNginx] Start streaming
[16-03-2020 14:37:42.562] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream" in 6000ms
[16-03-2020 14:37:48.569] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream"
[16-03-2020 14:37:48.571] [INFO ] [    repeatToLocalNginx] Start streaming
frame= 1407 fps= 10 q=-0.0 size=   27572kB time=00:02:18.70 bitrate=1628.5kbits/s speed=0.984x   
```
(retrying over and over)

Funny enough, the streaming vial VLC and `rtmp://192.168.x.x:1935/live/usbcam.stream` works but stutters every time ffmpeg does retry.

The webibnterface states this error: 
![Bildschirmfoto 2020-03-16 um 14 39 27](https://user-images.githubusercontent.com/9745239/76763777-0d0d0800-6794-11ea-89df-bc0538560551.png)

**Comment by ioppermann** [comment]
This is really interesting ... 🤔 

Please enable the debug logging (`-e RS_DEBUG=true`) as described on https://datarhei.github.io/restreamer/docs/references-environment-vars.html#rs_debug so we can see why ffmpeg is struggling with this.

**Comment by codmpm** [comment]
```
sudo docker run -it --rm \
     --name restreamer \
     -e "RS_USERNAME=admin" \
     -e "RS_PASSWORD=admin" \
     -e "RS_MODE=USBCAM" \
     -e "RS_USBCAM_WIDTH=1280" \
     -e "RS_USBCAM_HEIGHT=720" \
     -e "RS_USBCAM_FPS=30" \
     -e RS_DEBUG=true \
     -p 8080:8080 \
     -v /mnt/restreamer/db:/restreamer/db \
     -v /opt/vc:/opt/vc \
     --tmpfs /tmp/hls \
     --device /dev/vchiq \
     --device /dev/video0:/dev/video \
     datarhei/restreamer-rpi:0.6.2
```

Still the same error as soon as I start the stream: 

```
> Restreamer@0.6.2 start /restreamer
> node ./src/start

[16-03-2020 17:01:55.492] [INFO ] [                 start] Enabled logging to 24-linux-arm
[16-03-2020 17:01:55.566] [INFO ] [                 NGINX] Enabled logging to 24-linux-arm
[16-03-2020 17:01:56.103] [INFO ] [            Restreamer] Enabled logging to 24-linux-arm
[16-03-2020 17:01:56.106] [INFO ] [          WSController] Enabled logging to 24-linux-arm
[16-03-2020 17:01:56.329] [INFO ] [             Webserver] Enabled logging to 24-linux-arm
[16-03-2020 17:01:56.337] [INFO ] [             Webserver] Enabled logging to 24-linux-arm
[16-03-2020 17:01:56.503] [INFO ] [        RestreamerData] Enabled logging to 24-linux-arm
[16-03-2020 17:01:56.505] [INFO ] Debugging enabled. Check the /debug path in the web interface.
[16-03-2020 17:01:56.507] [INFO ]      _       _             _           _ 
[16-03-2020 17:01:56.509] [INFO ]   __| | __ _| |_ __ _ _ __| |___   ___(_)
[16-03-2020 17:01:56.510] [INFO ]  / _  |/ _  | __/ _  |  __|  _  |/  _ | |
[16-03-2020 17:01:56.511] [INFO ] | (_| | (_| | || (_| | |  | | | |  __/| |
[16-03-2020 17:01:56.512] [INFO ] |_____|_____|_||_____|_|  |_| |_|____||_|
[16-03-2020 17:01:56.514] [INFO ] 
[16-03-2020 17:01:56.515] [INFO ] Restreamer v0.6.2
[16-03-2020 17:01:56.516] [INFO ] 
[16-03-2020 17:01:56.517] [INFO ] ENVIRONMENTS
[16-03-2020 17:01:56.518] [INFO ] More information in our Docs
[16-03-2020 17:01:56.520] [INFO ] 
[16-03-2020 17:01:56.521] [INFO ] [                   ENV] RS_NODEJS_PORT = 3000 (using default) - Webserver port of application.
[16-03-2020 17:01:56.522] [INFO ] [                   ENV] RS_NODEJS_ENV = prod (using default) - Node.js Environment ('dev' or 'prod').
[16-03-2020 17:01:56.523] [INFO ] [                   ENV] RS_LOGLEVEL = 3 (using default) - Logging level (0=no logging, 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG).
[16-03-2020 17:01:56.524] [INFO ] [                   ENV] RS_TIMEZONE = Europe/Berlin (using default) - Set the timezone. Accepts Olson timezone IDs.
[16-03-2020 17:01:56.525] [INFO ] [                   ENV] RS_SNAPSHOT_INTERVAL = 1m (using default) - Interval for new snapshots (in milliseconds, use suffix 's' for seconds, 'm' for minutes). Use a value of 0 to disable snapshots.
[16-03-2020 17:01:56.527] [INFO ] [                   ENV] RS_USERNAME = admin - Username for the backend.
[16-03-2020 17:01:56.528] [INFO ] [                   ENV] RS_PASSWORD = ****** - Password for the backend.
[16-03-2020 17:01:56.529] [INFO ] [                   ENV] RS_TOKEN =  (using default) - Token for pushing an RTMP stream.
[16-03-2020 17:01:56.530] [INFO ] [                   ENV] RS_DEBUG_HEAPDUMPS = false (using default) - Create heapdumps of application.
[16-03-2020 17:01:56.531] [INFO ] [                   ENV] RS_DEBUG = true - Enables debug reporting.
[16-03-2020 17:01:56.532] [INFO ] [                   ENV] RS_AUDIO = auto (using default) - Audio track handling: auto, none (remove audio), silence (force silence), aac (force AAC), mp3 (force MP3).
[16-03-2020 17:01:56.533] [INFO ] [                   ENV] RS_HTTPS = false (using default) - Enables HTTPS support for admin interface and embeddable player.
[16-03-2020 17:01:56.535] [INFO ] [                   ENV] RS_INPUTSTREAM =  (using default) - Automatically start pulling from this stream on a fresh Restreamer installation.
[16-03-2020 17:01:56.536] [INFO ] [                 NGINX] Starting ...
[16-03-2020 17:01:56.926] [INFO ] [                 NGINX] Successfully started
[16-03-2020 17:01:56.930] [INFO ] [        RestreamerData] Checking jsondb file...
[16-03-2020 17:01:56.984] [INFO ] [              publicIP] Retrieving public IP ...
[16-03-2020 17:01:56.995] [INFO ] [             Webserver] Starting ...
[16-03-2020 17:01:57.111] [INFO ] [             Webserver] Running on port 3000
[16-03-2020 17:01:57.167] [INFO ] [              publicIP] Found public IP: x.x.x.xcd /op
[16-03-2020 17:01:57.261] [INFO ] [       checkForUpdates] Update checking succeeded. Update available
ffmpeg started on 2020-03-16 at 16:01:59
Report written to "/restreamer/src/webserver/public/debug/ffmpeg-20200316-160159.log"
ffmpeg version 4.1.5 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --bindir=/usr/local//bin --extra-cflags=-I/usr/local//include --extra-ldflags=-L/usr/local//lib --prefix=/usr/local/ --enable-nonfree --enable-gpl --enable-version3 --enable-libmp3lame --enable-libx264 --enable-omx --enable-omx-rpi --enable-mmal --enable-openssl --enable-postproc --enable-small --enable-static --disable-debug --disable-doc --disable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[video4linux2,v4l2 @ 0x2a27a80] The driver changed the time per frame from 1/30 to 1/10
Input #0, video4linux2,v4l2, from '/dev/video':
  Duration: N/A, start: 7937.664970, bitrate: 147456 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 1280x720, 147456 kb/s, 10 fps, 10 tbr, 1000k tbn, 1000k tbc
Input #1, lavfi, from 'anullsrc=r=44100:cl=mono':
  Duration: N/A, start: 0.000000, bitrate: 352 kb/s
    Stream #1:0: Audio: pcm_u8, 44100 Hz, mono, u8, 352 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_omx))
  Stream #1:0 -> #0:1 (pcm_u8 (native) -> aac (native))
Press [q] to stop, [?] for help
[h264_omx @ 0x2a2fc00] Using OMX.broadcom.video_encode
Output #0, flv, to 'rtmp://127.0.0.1:1935/live/usbcam.stream':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (h264_omx) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1280x720, q=2-31, 4882 kb/s, 30 fps, 1k tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.35.100 h264_omx
    Stream #0:1: Audio: aac ([10][0][0][0] / 0x000A), 44100 Hz, mono, fltp, 69 kb/s
    Metadata:
      encoder         : Lavc58.35.100 aac
[16-03-2020 17:02:08.980] [INFO ] [    repeatToLocalNginx] Start streamingkbits/s speed=0.999x    
[16-03-2020 17:02:24.002] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream" in 6000ms
[16-03-2020 17:02:30.010] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream"
[16-03-2020 17:02:30.013] [INFO ] [    repeatToLocalNginx] Start streaming
[16-03-2020 17:02:42.373] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtmp://127.0.0.1/live/usbcam.stream" in 6000ms
[16-03-2020 17:02:44.036] [INFO ] [    repeatToLocalNginx] Stop streaming3kbits/s speed=0.987x    
[16-03-2020 17:02:44.972] [ERROR] [             Webserver] Error: Not Found /images/live.jpg5x    
av_interleaved_write_frame(): Connection reset by peer44.36 bitrate=1626.9kbits/s speed=0.987x    
    Last message repeated 1 times
[flv @ 0x2a2e880] Failed to update header with correct duration.
[flv @ 0x2a2e880] Failed to update header with correct filesize.
Error writing trailer of rtmp://127.0.0.1:1935/live/usbcam.stream: Connection reset by peer
frame=  451 fps= 10 q=-0.0 Lsize=    8831kB time=00:00:44.46 bitrate=1626.8kbits/s speed=0.987x    
video:8823kB audio:8kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000343%
[aac @ 0x2a311b0] Qavg: 65520.469
Exiting normally, received signal 2.
```

Btw: `datarhei/restreamer-armv7l:latest` works without any problem...

**Comment by codmpm** [comment]
I think this should be the _important_ part of the log: 

```
Opening an input file: rtmp://127.0.0.1/live/usbcam.stream.
[NULL @ 0x1863940] Opening 'rtmp://127.0.0.1/live/usbcam.stream' for reading
[rtmp @ 0x18640b0] No default whitelist set
[tcp @ 0x1864620] No default whitelist set
[tcp @ 0x1864620] Original list of addresses:
[tcp @ 0x1864620] Address 127.0.0.1 port 1935
[tcp @ 0x1864620] Interleaved list of addresses:
[tcp @ 0x1864620] Address 127.0.0.1 port 1935
[tcp @ 0x1864620] Starting connection attempt to 127.0.0.1 port 1935
[tcp @ 0x1864620] Successfully connected to 127.0.0.1 port 1935
[rtmp @ 0x18640b0] Handshaking...
[rtmp @ 0x18640b0] Type answer 3
[rtmp @ 0x18640b0] Server version 13.14.10.13
[rtmp @ 0x18640b0] Proto = rtmp, path = /live/usbcam.stream, app = live, fname = usbcam.stream
[rtmp @ 0x18640b0] Window acknowledgement size = 5000000
[rtmp @ 0x18640b0] Max sent, unacked = 5000000
[rtmp @ 0x18640b0] New incoming chunk size = 4000
[rtmp @ 0x18640b0] Creating stream...
[rtmp @ 0x18640b0] Sending play command for 'usbcam.stream'
[flv @ 0x1863940] Format flv probed with size=2048 and score=100
[flv @ 0x1863940] Before avformat_find_stream_info() pos: 13 bytes read:2051 seeks:0 nb_streams:0
[flv @ 0x1863940] Unknown type |RtmpSampleAccess
[NULL @ 0x1894750] nal_unit_type: 7(SPS), nal_ref_idc: 1
[NULL @ 0x1894750] nal_unit_type: 8(PPS), nal_ref_idc: 1
[h264 @ 0x1894750] nal_unit_type: 7(SPS), nal_ref_idc: 1
[h264 @ 0x1894750] nal_unit_type: 8(PPS), nal_ref_idc: 1
[h264 @ 0x1894750] nal_unit_type: 5(IDR), nal_ref_idc: 1
[h264 @ 0x1894750] Format yuv420p chosen by get_format().
[h264 @ 0x1894750] Reinit context to 1280x720, pix_fmt: yuv420p
[h264 @ 0x1894750] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
[h264 @ 0x1894750] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
[h264 @ 0x1894750] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
[h264 @ 0x1894750] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
[h264 @ 0x1894750] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
[h264 @ 0x1894750] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1
[flv @ 0x1863940] All info found
[flv @ 0x1863940] After avformat_find_stream_info() pos: 842318 bytes read:842318 seeks:0 frames:290
Input #0, flv, from 'rtmp://127.0.0.1/live/usbcam.stream':
  Metadata:
    Server          : NGINX RTMP (github.com/arut/nginx-rtmp-module)
    displayWidth    : 1280
    displayHeight   : 720
    fps             : 30
    profile         : 
    level           : 
  Duration: 00:00:00.00, start: 227.044000, bitrate: N/A
    Stream #0:0, 249, 1/1000: Audio: aac, 44100 Hz, mono, fltp, 68 kb/s
    Stream #0:1, 41, 1/1000: Video: h264, yuv420p(progressive), 1280x720, 4881 kb/s, 30 fps, 10 tbr, 1k tbn
Successfully opened the file.
Parsing a group of options: output url rtmp://127.0.0.1:1935/hls/live.stream.
Applying option map_metadata (set metadata information of outfile from infile) with argument -1.
Applying option metadata (add metadata) with argument application=datarhei/Restreamer.
Applying option f (force format) with argument flv.
Applying option map (set input stream mapping) with argument 0:1.
Applying option codec:v (codec name) with argument h264_omx.
Applying option b:v (video bitrate (please use -b:v)) with argument 2048k.
Applying option r (set frame rate (Hz value, fraction or abbreviation)) with argument 30.
Applying option pix_fmt (set pixel format) with argument yuv420p.
Applying option an (disable audio) with argument 1.
Successfully parsed a group of options.
Opening an output file: rtmp://127.0.0.1:1935/hls/live.stream.
[rtmp @ 0x1867ce0] No default whitelist set
[tcp @ 0x1891b70] No default whitelist set
[tcp @ 0x1891b70] Original list of addresses:
[tcp @ 0x1891b70] Address 127.0.0.1 port 1935
[tcp @ 0x1891b70] Interleaved list of addresses:
[tcp @ 0x1891b70] Address 127.0.0.1 port 1935
[tcp @ 0x1891b70] Starting connection attempt to 127.0.0.1 port 1935
[tcp @ 0x1891b70] Successfully connected to 127.0.0.1 port 1935
[rtmp @ 0x1867ce0] Handshaking...
[rtmp @ 0x1867ce0] Type answer 3
[rtmp @ 0x1867ce0] Server version 13.14.10.13
[rtmp @ 0x1867ce0] Proto = rtmp, path = /hls/live.stream, app = hls, fname = live.stream
[rtmp @ 0x1867ce0] Window acknowledgement size = 5000000
[rtmp @ 0x1867ce0] Max sent, unacked = 5000000
[rtmp @ 0x1867ce0] New incoming chunk size = 4000
[rtmp @ 0x1867ce0] Releasing stream...
[rtmp @ 0x1867ce0] FCPublish stream...
[rtmp @ 0x1867ce0] Creating stream...
[rtmp @ 0x1867ce0] Sending publish command for 'live.stream'
Successfully opened the file.
[h264_mmal @ 0x19e0d60] Format yuv420p chosen by get_format().
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (h264_mmal) -> h264 (h264_omx))
Error while opening decoder for input stream #0:1 : Unknown error occurred
[AVIOContext @ 0x18ad1b0] Statistics: 0 seeks, 0 writeouts
[rtmp @ 0x1867ce0] UnPublishing stream...
[rtmp @ 0x1867ce0] Deleting stream...
[AVIOContext @ 0x1866350] Statistics: 842318 bytes read, 0 seeks
[rtmp @ 0x18640b0] Deleting stream...
```

`ffmpeg-20200316-163044.log` is from when the docker container started. `ffmpeg-20200316-163437.log` is one of the files which got created on every retry.


[ffmpeg-20200316-163437.log](https://github.com/datarhei/restreamer/files/4339234/ffmpeg-20200316-163437.log)
[ffmpeg-20200316-163044.log](https://github.com/datarhei/restreamer/files/4339235/ffmpeg-20200316-163044.log)

**Comment by ioppermann** [comment]
The culprit is, that you should set the video to "copy" in the stream options. You don't need to re-encode the video as it is already H264 encoded.
![Screenshot_2020-03-16 Restreamer](https://user-images.githubusercontent.com/57445/76787442-54f25600-67b9-11ea-8981-1108aa9f53a8.png)
The MMAL decoder only works with the `--privileged` docker option, however the encoding of the USB camera stream will not work anymore.

**Comment by codmpm** [comment]
Thank you so much for your patience.

Obviously I misunderstood something: I thought I could not _copy_ as my Webcam is a recent Logitech C920 which has [no hardware encoding capabilities anymore](https://www.logitech.com/en-us/video-collaboration/resources/think-tank/articles/article-logitech-and-h264-encoding.html). With the _default_ arm image I'm using h.264 as the encoding option.

But if I get you right, the rtmp-stream is already h264 as the ffmpeg in the background, which generates ist from the usb cam, already does the encoding, right?

I will test this tomorrow, the Pi is currently in use with Octoprint for the 3D printer.

**Comment by ioppermann** [comment]
Yes, the stream from the camera is encoded in the background and pushed to the local RTMP server from where you pull it in the Restreamer interface. No need to encode it again.

The default arm image is actually doing the same, but everything is happening on the CPU (with `libx264`). In this case you might have encoded it twice. With CPU encoding this usually doesn't pose a problem (besides the high CPU load) because the encoding instances will not collide and step on each others foot. With HW acceleration it is a bit more tricky.

This isn't clearly stated in the documentation and I will adjust the documentation accordingly. The documentation for the USB camera and Raspi camera are based on an older version of Restreamer where explicit re-encoding of the stream wasn't possible yet.

Sorry for the confusion.

PS: I re-pushed the original Docker image (`datarhei/restreamer-rpi:0.6.2`) without the ffmpeg output on the console.

**Comment by codmpm** [comment]
Ohhhh... that's where I went the wrong my in my head.

Here the CPU Load with `datarhei/restreamer-armv7l:latest` using only copy.
![Bildschirmfoto 2020-03-17 um 09 32 29](https://user-images.githubusercontent.com/9745239/76837113-43996000-6832-11ea-96b7-4745198ae78a.png)

and here it is with `datarhei/restreamer-rpi:0.6.2` on the same Pi4/2GB
![Bildschirmfoto 2020-03-17 um 09 35 08](https://user-images.githubusercontent.com/9745239/76837323-aab71480-6832-11ea-998d-e1125dd3608d.png)

Both working on my octopi install without `sudo`.

```
docker run -d \
     --name restreamer \
     -e "RS_USERNAME=admin" \
     -e "RS_PASSWORD=admin" \
     -e "RS_MODE=USBCAM" \
     -e "RS_USBCAM_WIDTH=1280" \
     -e "RS_USBCAM_HEIGHT=720" \
     -e "RS_USBCAM_FPS=30" \
     -p 8080:8080 \
     -v /mnt/restreamer/db:/restreamer/db \
     -v /opt/vc:/opt/vc \
     --tmpfs /tmp/hls \
     --device /dev/vchiq \
     --device /dev/video0:/dev/video \
     datarhei/restreamer-rpi:0.6.2
```

So, the stream settings in the webinterface are _only_ for the output stream and, because the stream from the USB cam is encoded anyways, I only need to copy `rtmp://127.0.0.1/live/usbcam.stream`.

Works, great. Thank you!

As I have the player faced towards the internet (https, auth) to check the printer externally, how do I change the bitrate of the usb camera encoding process?

**Comment by ioppermann** [comment]
Great that it works now 🎉 

You can change the bitrate with the environment variable `RS_USBCAM_BITRATE`. All other environment variables regarding the UBS camera are described here: https://datarhei.github.io/restreamer/docs/guides-usb-camera.html#environment-variables

In case of HW accerelation, the environment variable `RS_USBCAM_H264PRESET` is ignored.

**Comment by codmpm** [comment]
Oh, sorry, should have checked the documentation first.
Thank you very very much!

Are you planing to make the pi version a regular version? Of course there must to be more idiot-proofness ;-)

**Comment by codmpm** [comment]
Sadly the stream stops after some time (~30m?) and the player states this error: 

```
There was a problem trying to load the video.
Error code: hls:networkError_manifestLoadError
```

The docker container, at least with standard logging, does not say anything special: 
```
[17-03-2020 12:51:05.964] [INFO ] [                 NGINX] Starting ...
[17-03-2020 12:51:06.278] [INFO ] [                 NGINX] Successfully started
[17-03-2020 12:51:06.281] [INFO ] [        RestreamerData] Checking jsondb file...
[17-03-2020 12:51:06.335] [INFO ] [              publicIP] Retrieving public IP ...
[17-03-2020 12:51:06.346] [INFO ] [             Webserver] Starting ...
[17-03-2020 12:51:06.457] [INFO ] [             Webserver] Running on port 3000
[17-03-2020 12:51:06.505] [INFO ] [              publicIP] Found public IP: 87.139.63.17
[17-03-2020 12:51:06.632] [INFO ] [       checkForUpdates] Update checking succeeded. Update available
[17-03-2020 12:51:25.673] [INFO ] [    repeatToLocalNginx] Start streaming
[17-03-2020 12:51:55.814] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 12:52:56.795] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 12:53:57.520] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 12:54:58.708] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 12:55:59.729] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 12:57:00.701] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 12:57:55.455] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 12:58:56.251] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 12:59:57.363] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 13:00:58.028] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 13:01:58.687] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 13:02:59.423] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 13:04:00.017] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 13:04:55.050] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 13:05:55.680] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 13:06:56.511] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
[17-03-2020 13:07:57.428] [INFO ] [              snapshot] Updated. Next scheduled update in 60000ms.
```

Do you have any advice regarding this?

**Comment by ioppermann** [comment]
This looks like the background ffmpeg process that is encoding the raw video from the USB camera stopped unexpectedly.

**Comment by codmpm** [comment]
Thank you again and sorry for not getting back quickly. Currently work is very demanding because of the global situation. I will get back to this as fast as I can.

**Comment by codmpm** [comment]
So, back again.

As I currently have the problem to get `player.html` to run, I've first investigated this way instead of experimenting with the pi version.
The webcam stream is working - doublechecked with VLC on `rtmp://192.168.xx.xx:1935/live/usbcam.stream` and `-p 1935:1935` - but the player is loading and loading. `/images/live.jpg` is working though.

Firefox is just showing the loading animation and Safari shows 
![Bildschirmfoto 2020-03-23 um 16 28 27](https://user-images.githubusercontent.com/9745239/77333217-5ffe3680-6d23-11ea-88f6-fb332d825297.png)

Funny enough, Chrome is working... as I've just dicsovered now.
I've tried `datarhei/restreamer-armv7l:latest` and `datarhei/restreamer-armv7l:0.6.2` same result.
Seems to be the same problem as in #152.

**Comment by ioppermann** [comment]
Is there any audio involved?

**Comment by codmpm** [comment]
Here is my complete docker call: 

```
docker run -d \
    --restart always \
    --name restreamer \
    -e "RS_USERNAME=admin" \
    -e "RS_PASSWORD=admin" \
    -e "RS_MODE=USBCAM" \
    -e "RS_USBCAM_WIDTH=1280" \
    -e "RS_USBCAM_HEIGHT=720" \
    -e "RS_USBCAM_FPS=25" \
    -e "RS_USBCAM_BITRATE=2500000" \
    -e "RS_USBCAM_AUDIO=false" \
    -p 8080:8080 \
    -p 1935:1935 \
    -v /mnt/restreamer/db:/restreamer/db \
    --device /dev/video0:/dev/video \
    datarhei/restreamer-armv7l:latest
```

Only thing I did is `"RS_USBCAM_AUDIO=false"`....

**Comment by ioppermann** [comment]
OK, I can reproduce this behaviour. It seems that the nginx_rtmp module is adding an empty audio channel to the HLS files if the input stream doesn't have an audio channel 🤯  and Firefox doesn't like this.

If you choose `auto` or `copy` for audio, then it should work.

**Comment by codmpm** [comment]
Sadly I can not confirm. Neither `copy` nor `auto` did the trick. I do not get the loading animation anymore but only a still frame now.

Also, the "Image URL" is not displayed correctly.

**Comment by ioppermann** [comment]
Oh, yes. That's true. The stream doesn't move. I have to investigate this.

I noticed that the audio stream from the USB cam (it's AAC silence if you don't select an audio source) is first and then the video stream. This may also confuse the nginx-rtmp module.

**Comment by ioppermann** [comment]
@codmpm I found out where the problem is. The USB camera is delivering the image in the YUV422 format. Safari and Firefox do not support decoding this format. Before encoding the stream from the USB camera, the format needs to be converted to YUV420. Then it works in all browsers.

I already added a fix to master.

**Comment by codmpm** [comment]
Great to hear, thank you so much for your work!
So should I just use `datarhei/restreamer-rpi:latest`?

**Comment by ioppermann** [comment]
I didn't push a new Docker image yet. Probably on the weekend I'll be able to make a new release.

**Comment by ioppermann** [comment]
@codmpm I made a new release with the fix. Please use either `docker pull datarhei/restreamer-armv7l:0.6.4` (without HW acceleration) or `docker pull datarhei/restreamer-rpi:0.6.4` (with HW acceleration). For HW acceleration, refer to the guide in the comment https://github.com/datarhei/restreamer/issues/148#issuecomment-597197503 above.

**Comment by codmpm** [comment]
It Works! Great!!

Thank you so much 👍

**Comment by ioppermann** [comment]
@codmpm Is your project with the Restreamer public and would it be possible that you share it? We could share it on our social media channels.

**Comment by codmpm** [comment]
I've documented it here so far: 

https://community.octoprint.org/t/using-ffmpeg-for-webcam-streaming-and-timelapse-support/5321/16

I would wirte a blog entry (german) for that... but my time is somewhat limited because of the pandemic...
